#!/usr/bin/env node
// ============================================================
// build.js - Assembles src/ into deployable index.js
// ============================================================
const fs = require('fs');
const path = require('path');

// Read source files
const templateHtml = fs.readFileSync(path.join(__dirname, 'src', 'template.html'), 'utf-8');
const workerCode = fs.readFileSync(path.join(__dirname, 'src', 'worker.js'), 'utf-8');

// Escape the HTML for use as a JavaScript template literal
function escapeForTemplateLiteral(str) {
    return str
        .replace(/\\/g, '\\\\')      // backslash
        .replace(/`/g, '\\`')         // backtick
        .replace(/\${/g, '\\${')     // template expression
        .replace(/\r\n?/g, '\n');    // normalize line endings
}

const escapedHtml = escapeForTemplateLiteral(templateHtml);
const htmlPageDecl = `// HTML 页面模板 (auto-generated by build.js)\nconst HTML_PAGE = \`\n${escapedHtml}\n\`;\n\n`;

// Replace the placeholder comment
const finalCode = workerCode.replace('/* __HTML_PAGE__ will be injected by build.js */', htmlPageDecl);

// Write to deployable index.js
const outputPath = path.join(__dirname, 'index.js');
fs.writeFileSync(outputPath, finalCode, 'utf-8');

const htmlSize = Buffer.byteLength(templateHtml, 'utf-8');
const workerSize = Buffer.byteLength(workerCode, 'utf-8');
const totalSize = Buffer.byteLength(finalCode, 'utf-8');

console.log('=== Build Complete ===');
console.log(`  template.html: ${(htmlSize / 1024).toFixed(1)} KB (${templateHtml.split('\n').length} lines)`);
console.log(`  worker.js:     ${(workerSize / 1024).toFixed(1)} KB (${workerCode.split('\n').length} lines)`);
console.log(`  index.js:      ${(totalSize / 1024).toFixed(1)} KB (${finalCode.split('\n').length} lines)`);
console.log('Output: index.js');
